baseURL = 'https://brian936826-lang.github.io/'
languageCode = 'zh-CN'
title = 'Brian'
theme = 'PaperMod'

[params]
  author = 'Brian'
  description = '个人网站'
  defaultTheme = 'auto'

  [params.profileMode]
    enabled = true
    title = 'Brian'
    subtitle = 'SUSTech'
    imageUrl = '/images/avatar.jpg'
    imageWidth = 150
    imageHeight = 150

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/brian936826-lang'
  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:brian936826@gmail.com'

[[menu.main]]
  name = '首页'
  url = '/'
  weight = 1
[[menu.main]]
  name = '博客'
  url = '/posts/'
  weight = 2
[[menu.main]]
  name = '作品'
  url = '/projects/'
  weight = 3
[[menu.main]]
  name = '关于'
  url = '/about/'
  weight = 4
